version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20  
    commands:
      - npm install -g nodemon
  pre_build:
    commands:
      - npm install
artifacts:
  files:
    - index.js
    - package.json
    - node_modules/*
    - config/*
    - middleware/*
    - models/*
    - routes/*
    - views/*
